/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import br.com.proagende.conexao.Conexao;
import dao.AgendamentoDAO;
import dao.ClienteDAO;
import dao.ServicoDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.Cliente;
import model.Servico;
import java.util.List;

/**
 *
 * @author IgorP
 */
public class CadastroAgendamento extends javax.swing.JFrame {

    /**
     * Creates new form CadastroAgendamento
     */
    public CadastroAgendamento() {
        initComponents();
        //Chamando o método para preecnher o comboBox
        carregarClientes();
        carregarServicos();
    }

    private java.util.List<Cliente> listaClientes = new ArrayList<>();
    private java.util.List<Servico> listaServicos = new ArrayList<>();

    //Método responsável por preencher o comboBox(Nome) da Tela com os dados do Banco de Dados
    private void carregarClientes() {
        ClienteDAO dao = new ClienteDAO();
        listaClientes = dao.listarTodos();

        cmbNome.removeAllItems();
        cmbNome.addItem("Selecionar");

        for (Cliente cliente : listaClientes) {
            cmbNome.addItem(cliente.getNome());   // ← MUDE PARA ISSO
        }
    }

    //Método responsável por preencher o outro comboBox(Servico) da Tela com os dados do Banco de Dados
    private void carregarServicos() {
        ServicoDAO dao = new ServicoDAO();
        listaServicos = dao.listarTodos();  // retorna List<Servico> com id + nome

        cmbServico.removeAllItems();
        cmbServico.addItem("Selecionar");

        if (listaServicos != null && !listaServicos.isEmpty()) {
            for (Servico servico : listaServicos) {
                cmbServico.addItem(servico.getNome());   // ← use getNome() para evitar erro de tipo
            }
        } else {
            System.out.println("Nenhum serviço encontrado no banco.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbNome = new javax.swing.JComboBox<>();
        cmbServico = new javax.swing.JComboBox<>();
        cmbStatus = new javax.swing.JComboBox<>();
        btnConfirmar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtData = new javax.swing.JFormattedTextField();
        txtHora = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(40, 120, 40, 120));

        jLabel1.setFont(new java.awt.Font("DialogInput", 1, 28)); // NOI18N
        jLabel1.setText(" Novo Agendamento");

        jLabel2.setFont(new java.awt.Font("DialogInput", 2, 20)); // NOI18N
        jLabel2.setText("Nome:");

        jLabel3.setFont(new java.awt.Font("DialogInput", 2, 20)); // NOI18N
        jLabel3.setText("Serviço:");

        jLabel4.setFont(new java.awt.Font("DialogInput", 2, 20)); // NOI18N
        jLabel4.setText("Data:");

        jLabel5.setFont(new java.awt.Font("DialogInput", 2, 20)); // NOI18N
        jLabel5.setText("Hora:");

        jLabel6.setFont(new java.awt.Font("DialogInput", 2, 20)); // NOI18N
        jLabel6.setText("Status:");

        cmbNome.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar", "Nome Cadastrado 1", "Nome Cadastrado 2", "Nome Cadastrado 3" }));

        cmbServico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar", "Serviço Cadastrado 1", "Serviço Cadastrado 2", "Serviço Cadastrado 3" }));

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar", "Confirmado", "Cancelado", "Pendente", " " }));

        btnConfirmar.setFont(new java.awt.Font("DialogInput", 2, 18)); // NOI18N
        btnConfirmar.setText("CONFIRMAR");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("DialogInput", 2, 18)); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        try {
            txtData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtData.setToolTipText("14/12/1990");

        try {
            txtHora.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtHora.setToolTipText("10:45");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbServico, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1)
                                    .addComponent(cmbNome, 0, 330, Short.MAX_VALUE)
                                    .addComponent(txtData))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtHora))))
                .addGap(105, 105, 105))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        String nomeSelecionado = cmbNome.getSelectedItem().toString();
        String servicoSelecionado = cmbServico.getSelectedItem().toString();
        String dataTexto = txtData.getText();
        String horaTexto = txtHora.getText();
        String status = cmbStatus.getSelectedItem().toString();

        // Validação
        if (nomeSelecionado.equals("Selecionar") || servicoSelecionado.equals("Selecionar") || dataTexto.isEmpty() || horaTexto.isEmpty() || status.equals("Selecionar")) {
            JOptionPane.showMessageDialog(this, "Por favor, preencha todos os campos!");
            return;
        }

        try {
            // Converter DATA
            java.time.format.DateTimeFormatter formatterData
                    = java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy");

            java.time.LocalDate data
                    = java.time.LocalDate.parse(dataTexto, formatterData);

            // Converter HORA
            java.time.format.DateTimeFormatter formatterHora
                    = java.time.format.DateTimeFormatter.ofPattern("HH:mm");

            java.time.LocalTime hora
                    = java.time.LocalTime.parse(horaTexto, formatterHora);

            // Formato correto para MySQL
            String dataHora = data.toString() + " " + hora.toString() + ":00";

            // Buscar o ID do cliente na lista que foi carregada
            int idCliente = 0;
            for (Cliente c : listaClientes) {
                if (c.getNome().equals(nomeSelecionado)) {
                    idCliente = c.getIdCliente();  // use getIdCliente() porque sua classe usa idCliente
                    break;
                }
            }

            // Buscar o ID do serviço na lista carregada
            int idServico = 0;
            for (Servico s : listaServicos) {
                if (s.getNome().equals(servicoSelecionado)) {
                    idServico = s.getIdServico();   // ← MUDE PARA getIdServico() aqui
                    break;
                }
            }

            // Verificação de segurança
            if (idCliente == 0 || idServico == 0) {
                JOptionPane.showMessageDialog(this,
                        "Não foi possível encontrar o ID do cliente ou serviço selecionado.\n"
                        + "Cliente selecionado: " + nomeSelecionado + "\n"
                        + "Serviço selecionado: " + servicoSelecionado,
                        "Erro de identificação",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }

            // DAO
            AgendamentoDAO agendamentoDAO = new AgendamentoDAO();
            agendamentoDAO.salvarAgendamento(idServico, idCliente, dataHora, status);

            JOptionPane.showMessageDialog(this, "Agendamento salvo com sucesso!");

            // Limpar campos
            cmbNome.setSelectedIndex(0);
            cmbServico.setSelectedIndex(0);
            txtData.setText("");
            txtHora.setText("");
            cmbStatus.setSelectedIndex(0);

        } catch (java.time.format.DateTimeParseException e) {
            JOptionPane.showMessageDialog(this, "Data ou hora inválida!\nUse o formato correto.");
        }

    }//GEN-LAST:event_btnConfirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroAgendamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JComboBox<String> cmbNome;
    private javax.swing.JComboBox<String> cmbServico;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JFormattedTextField txtData;
    private javax.swing.JFormattedTextField txtHora;
    // End of variables declaration//GEN-END:variables
}
